### ISSUE TITLE
BattlEye filter

### ISSUE THREAD

**Issue by jus61** [d4n1ch/acd_SZ#2]
They also have the BattlEye filter

**Comment by d4n1ch** [comment]
Exile mod has its BE Filters and NO modification is need for my addon to work.

**Comment by jus61** [comment]
31.08.2015 19:53:23: jus61 (88.117.54.151:56374) xxxxxxxxxxxxxxxxxxxxxxx - #28 ""

if (acd_SPAWN_Kavala) then {
acd_SpawnKavala = createMarker ["SpawnKavala",[3874.3601,13280.8,18.125601]];
"SpawnKava"

**Comment by d4n1ch** [comment]
never triggered for me, i've fixed that by making markers to create only by server
