### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jus61** [d4n1ch/acd_SZ#3]
Error in expression <ystem_database_query_selectSingle;
if !(_cargoContainers isEqualTo []) then
{
[_>
18:51:04   Error position: <_cargoContainers isEqualTo []) then
{
[_>
18:51:04   Error Undefined variable in expression: _cargocontainers
18:51:04 File mpmissions__cur_mp.Altis\overwrites\exile_server\code\ExileServer_object_vehicle_database_load.sqf, line 86

**Comment by d4n1ch** [comment]
That error is Exile issue which means i suppose that variable _cargocontainers is not defined for vehicle that it is trying to load from DB.

**Comment by jus61** [comment]
ok thx
